/*
 * Vencord, a Discord client mod
 * Copyright (c) 2026 Vendicated and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

// Horizontal Server List by DiscordStyles (github.com/DiscordStyles/HorizontalServerList), bundled so it applies instantly with no network fetch
export const HSL_CSS = ":root {\n  --notices-height: 36px;\n  --serverlist-offset: var(--custom-guild-list-width);\n}\n\n.base__5e434[data-fullscreen=\"false\"] .content__5e434 {\n  margin-top: var(--serverlist-offset);\n  overflow: visible !important;\n}\n\n:fullscreen .content__5e434 {\n  margin: 0 !important;\n}\n\n.sidebar__5e434 {\n  border-radius: 0;\n  overflow: visible !important;\n}\n\n.guilds__5e434 {\n  transform-origin: 0 0;\n  bottom: unset;\n  left: 0;\n  rotate: -90deg;\n  height: 100vw !important;\n  position: absolute !important;\n\n  & .itemsContainer_ef3116, & .stack_dbd263 {\n    flex-direction: var(--HSL-server-direction);\n    justify-content: var(--HSL-server-alignment);\n  }\n}\n\n.tree_ef3116 {\n  padding-top: var(--HSL-top-padding, var(--size-sm));\n  justify-content: var(--HSL-server-alignment);\n}\n\n.wrapper__6e9f8, .folderPreview__48112, .folderIconWrapper__48112, .lowerBadge_cc5dd2, .upperBadge_cc5dd2 {\n  rotate: 90deg;\n}\n\n.childWrapper__6e9f8 {\n  rotate: 0deg;\n}\n\n.notice__6e2b9 {\n  height: var(--notices-height);\n\n  & + .content__5e434 {\n    --serverlist-offset: calc(var(--notices-height) + var(--custom-guild-list-width));\n  }\n}\n\n.container__5e434 > div[style]:not(.base__5e434) {\n  top: calc(var(--serverlist-offset) + var(--custom-app-top-bar-height));\n  pointer-events: none;\n  z-index: 1;\n  position: absolute;\n  width: 100vw !important;\n  height: var(--serverlist-offset) !important;\n\n  & .guilds__5e434 {\n    pointer-events: all;\n  }\n\n  & + .base__5e434 .content__5e434 {\n    margin-top: calc(var(--serverlist-offset) * 2);\n  }\n}";

// Bottom variant (same project), applied on top of HSL_CSS
export const HSL_BOTTOM_CSS = ".base__5e434[data-fullscreen=\"false\"] .content__5e434 {\n  margin-top: unset;\n  margin-bottom: var(--custom-guild-list-width);\n}\n\n#app-mount {\n  & .guilds__5e434 {\n    top: calc(100% + var(--custom-guild-list-width));\n  }\n}\n\n.base__5e434 > div[style]:not(.base__5e434) {\n  bottom: calc(var(--custom-guild-list-width) * 2);\n  top: unset;\n\n  & .guilds__5e434 {\n    top: calc(100% + var(--custom-guild-list-width) * 2) !important;\n  }\n\n  & + .base__5e434 .content__5e434 {\n    margin-top: unset;\n    margin-bottom: calc(var(--custom-guild-list-width) * 2);\n  }\n}";
